version: "3.8"

services:
  parcellaire-importer:
    image: ...
    environment:
      - "POSTGRES_USER=..."
      - "POSTGRES_PASSWORD=..."
      - "POSTGRES_DB=..."
      - "POSTGRES_HOST=..."
      - "POSTGRES_PORT=..."
      - "POSTGRES_SCHEMA=..."
      - "DOWNLOAD_URL=..."
      - "TEST_IMPORTER=..."
      - "MAX_PARALLEL_DL=..."
    volumes:
      - /data/parcellaire/importer:/tmp
    networks:
      - traefik-public
    command:
      - "cp"
      - "-v"
      - "/script/*"
      - "/tmp/."

  parcellaire-postgis:
    image: ...
    environment:
      - "POSTGRES_DB=..."
      - "POSTGRES_PORT=..."
      - "POSTGRES_USER=..."
      - "POSTGRES_PASSWORD=..."
    volumes:
      - /data/parcellaire/postgesql:/var/lib/postgresql/data
    networks:
      - traefik-public
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=2621kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"
      - "-c"
      - "max_parallel_maintenance_workers=2"
      # Pour logguer l'intégralité des requêtes effectuées sur la base
      # - "-c"
      # - "log_statement=all"
    shm_size: 2g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 10s

  parcellaire-api:
    image: ...
    networks:
      - traefik-public
    environment:
      - "POSTGRES_USER=..."
      - "POSTGRES_PASSWORD=..."
      - "POSTGRES_DB=..."
      - "POSTGRES_HOST=..."
      - "POSTGRES_PORT=..."
      - "POSTGRES_SCHEMA=..."
      - "API_PORT=..."
      - "API_KEY=..."
      - "MAX_FEATURE=..."
      - "VIEWER_URL=..."
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:${API_PORT}/status || exit 1",
        ]
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.port=8011"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rules=Host:..."

networks:
  traefik-public:
    external: true
