version: "3.8"

#####
# ⭐️ This file is not independent :
## 🟢 Docker-compose STACK mode, starts with
# docker login <registry_url>
# docker-compose -f docker-compose.common.yml -f docker-compose.stack.yml config > docker-stack.yml
# docker stack deploy parcellaire -c docker-stack.yml --with-registry-auth
###### 

# 🪧 Some information on this file : 
# See : https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  parcellaire-importer:
    image: ${STACK_IMAGE_IMPORTER}
    volumes:
      #- importer-data:/tmp
      - /data/parcellaire/importer:/tmp
    networks:
      - ${STACK_NETWORK_NAME}      
    command: /bin/bash /scripts/cmd.sh

  parcellaire-postgis:
    image: ${STACK_IMAGE_POSTGIS}
    # Exposition du port de la base de données pour test si nécessaire
    #ports:
    #  - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - ${STACK_NETWORK_NAME}      
    volumes:
      #- parcellaire-postgis-data:/var/lib/postgresql/data
      # 🚨 Please change the owner of /data/parcellaire/postgresql to 999:999 first.
      - /data/parcellaire/postgresql:/var/lib/postgresql/data

  parcellaire-api:
    image: ${STACK_IMAGE_API}
    #ports:
      #- "${API_PORT}:${API_PORT}"
    networks:
      - ${STACK_NETWORK_NAME}      
    deploy:
      labels:
      - "traefik.enable=true"
      - "traefik.port=${API_PORT}"
      - "traefik.frontend.rule=Host:${STACK_FRONTEND_DNS}"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=${STACK_NETWORK_NAME}"

# Activate this if you want to use volume instead of binded directories.
#volumes:
#  parcellaire-postgis-data:
#    name: parcellaire-postgis-data
#  importer-data:
#    name: importer-data

networks:
  ${STACK_NETWORK_NAME}:
    external: true
