version: "3.8"

#####
# ⭐️ This file is not independent :
## 🟢 Docker-compose DEV mode, starts with
# $ docker-compose [build|up -d|down] -f docker-compose.common.yml -f docker-compose.dev.yml
# OR
# $ docker-compose config docker-compose.common.yml -f docker-compose.dev.yml > docker-compose.yml
# $ docker-compose [build|up -d|down]
#####

# 🪧 Some information on this file : 
# See : https://docs.docker.com/compose/compose-file/compose-file-v3/

services:
  parcellaire-importer:
    container_name: parcellaire-express-importer
    build:
      context: ./importer  
    volumes:
      - importer-data:/tmp

  parcellaire-postgis:
    container_name: parcellaire-express-postgis
    build:
      context: ./postgis
      args:
        - POSTGRES_VERSION
        - POSTGIS_VERSION  
    shm_size: 2g
    volumes:
      - parcellaire-postgis-data:/var/lib/postgresql/data
  
  parcellaire-api:
    container_name: parcellaire-express-api
    # build command is ignored on docker stack. 
    build:
      context: ./api
      args:
        - api_port=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"

volumes:
  parcellaire-postgis-data:
    name: parcellaire-postgis-data
  importer-data:
    name: importer-data
